### PR TITLE
Front end homepage

### PR DESCRIPTION
**Pull request by NimeshaKahingala**

### CODE REVIEW

**Review by ZintisMay — APPROVED** [review]
image

image

Looks good to me.

**Review by RobertLRead — CHANGES_REQUESTED** [review]
I think this is nice, but I don't want to put it in the product until it is meaningfully doing something. Right now, nobody has any feature that they can gain by using this; so we don't want there to be a link to a "login" anywhere until the feature is supoorted. Maybe there is no such link. I don't mind this code being merged, as long as it is not visible to the user---we can keep it as "dead" code until we are ready to use it.

**Comment by Jbutler-helpful** [comment]
This looks good to me

**Review by RobertLRead — APPROVED** [review]
Thanks for removing links for now, @NimeshaKahingala !

**Pull request merged**
